// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zdybanka.Models;

#nullable disable

namespace Zdybanka.Migrations
{
    [DbContext(typeof(Lab1Context))]
    [Migration("20260426205350_AddPasswordReset")]
    partial class AddPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "admin", "organization_manager", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zdybanka.Models.Changeshistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Changedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Changedata")
                        .HasColumnType("json")
                        .HasColumnName("changedata");

                    b.Property<int?>("Eventid")
                        .HasColumnType("integer")
                        .HasColumnName("eventid");

                    b.HasKey("Id")
                        .HasName("changeshistory_pkey");

                    b.HasIndex("Eventid");

                    b.ToTable("changeshistory", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Categoryid")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Eventdate")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eventdate");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<int?>("Organizationid")
                        .HasColumnType("integer")
                        .HasColumnName("organizationid");

                    b.Property<int?>("Statusid")
                        .HasColumnType("integer")
                        .HasColumnName("statusid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("event_pkey");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Organizationid");

                    b.HasIndex("Statusid");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Eventcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("categoryname");

                    b.HasKey("Id")
                        .HasName("eventcategory_pkey");

                    b.ToTable("eventcategory", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Eventstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Statusname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("statusname");

                    b.HasKey("Id")
                        .HasName("eventstatus_pkey");

                    b.ToTable("eventstatus", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Organizationstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Statusname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("statusname");

                    b.HasKey("Id")
                        .HasName("organizationstatus_pkey");

                    b.ToTable("organizationstatus", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Eventid")
                        .HasColumnType("integer")
                        .HasColumnName("eventid");

                    b.Property<DateTime?>("Registrationdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registrationdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("registration_pkey");

                    b.HasIndex("Eventid");

                    b.HasIndex("Userid");

                    b.ToTable("registration", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zdybanka.Models.Userfavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Eventid")
                        .HasColumnType("integer")
                        .HasColumnName("eventid");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("userfavorite_pkey");

                    b.HasIndex("Eventid");

                    b.HasIndex(new[] { "Userid", "Eventid" }, "userfavorite_userid_eventid_key")
                        .IsUnique();

                    b.ToTable("userfavorite", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Organization", b =>
                {
                    b.HasBaseType("Zdybanka.Models.User");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Statusid")
                        .HasColumnType("integer")
                        .HasColumnName("statusid");

                    b.HasIndex("Statusid");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Zdybanka.Models.Changeshistory", b =>
                {
                    b.HasOne("Zdybanka.Models.Event", "Event")
                        .WithMany("Changeshistories")
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("changeshistory_eventid_fkey");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Zdybanka.Models.Event", b =>
                {
                    b.HasOne("Zdybanka.Models.Eventcategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("event_categoryid_fkey");

                    b.HasOne("Zdybanka.Models.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("Organizationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("event_organizationid_fkey");

                    b.HasOne("Zdybanka.Models.Eventstatus", "Status")
                        .WithMany("Events")
                        .HasForeignKey("Statusid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("event_statusid_fkey");

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Zdybanka.Models.Registration", b =>
                {
                    b.HasOne("Zdybanka.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("registration_eventid_fkey");

                    b.HasOne("Zdybanka.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("registration_userid_fkey");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zdybanka.Models.Userfavorite", b =>
                {
                    b.HasOne("Zdybanka.Models.Event", "Event")
                        .WithMany("Userfavorites")
                        .HasForeignKey("Eventid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("userfavorite_eventid_fkey");

                    b.HasOne("Zdybanka.Models.User", "User")
                        .WithMany("Userfavorites")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("userfavorite_userid_fkey");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zdybanka.Models.Organization", b =>
                {
                    b.HasOne("Zdybanka.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Zdybanka.Models.Organization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdybanka.Models.Organizationstatus", "Status")
                        .WithMany("Organizations")
                        .HasForeignKey("Statusid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("organization_statusid_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Zdybanka.Models.Event", b =>
                {
                    b.Navigation("Changeshistories");

                    b.Navigation("Registrations");

                    b.Navigation("Userfavorites");
                });

            modelBuilder.Entity("Zdybanka.Models.Eventcategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Zdybanka.Models.Eventstatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Zdybanka.Models.Organizationstatus", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Zdybanka.Models.User", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Userfavorites");
                });

            modelBuilder.Entity("Zdybanka.Models.Organization", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
